services:
  web:
    env_file:
      - ${DOCKER_ENV_FILE}
    container_name: ${APP_CONTAINER_NAME}
    build: .
    ports:
      - ${APP_LOCAL_PORT}:${APP_INTERNAL_PORT}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
  postgres:
    env_file:
      - ${DOCKER_ENV_FILE}
    container_name: ${DB_CONTAINER_NAME}
    build: ./src/db
    ports:
      - ${DB_LOCAL_PORT}:${DB_INTERNAL_PORT}
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${DB_USER} -d ${DB_NAME} -h localhost -p ${DB_INTERNAL_PORT}',
        ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
  redis:
    env_file:
      - ${DOCKER_ENV_FILE}
    container_name: ${REDIS_CONTAINER_NAME}
    image: redis:7
    ports:
      - ${REDIS_LOCAL_PORT}:${REDIS_INTERNAL_PORT}
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
