services:
  web:
    build: .
    ports: 
      - "3000:3000"
    env_file:
      - docker.env
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    container_name: news-page-postgres
    build: ./src/db
    ports: 
      - "5433:5432"
    env_file:
      - docker.env
    healthcheck:
      test:         [
          'CMD-SHELL',
          'pg_isready -U ${DB_USER} -d ${DEV_DB_NAME} -h ${DB_HOST} -p ${DB_PORT}',
        ]

      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s