psql << INITDB
CREATE USER $DB_USER WITH PASSWORD '$DB_PASSWORD';

CREATE DATABASE $TEST_DB_NAME WITH OWNER $DB_USER;

CREATE DATABASE $DEV_DB_NAME WITH OWNER $DB_USER;

CREATE DATABASE $PROD_DB_NAME WITH OWNER $DB_USER;
INITDB